global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'spring'
    scrape_interval: 5s
    metrics_path: '/metrics'
    honor_labels: true
    static_configs:
      - targets: ['10.200.10.1:9091']
      